openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/gkowalski/test/1.0.0
info:
  description: CD2H Notes DeIdentification API
  version: "1.0.0"
  title: CD2H Notes DeIdentification API
  contact:
    email: deid-notes@mcw.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /deid:
    post:
      tags:
        - developers
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can deidentify a given MedicalEHR Note
      parameters:
        - in: query
          name: deid
          description: note to DeIdentify
          required: false
          schema:
            $ref: '#/components/schemas/DeidRequest'
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeidResponse'
        '400':
          description: bad input parameter


  /blacklist:
    post:
      tags:
        - developers
      summary: Adds words to Black List
      operationId: addBlackList
      description:
        Added a list of Black List words to the deidentification process to always block
      parameters:
        - in: query
          name: deid
          description: list of black words
          required: false
          schema:
            type: string
      responses:
        '201':
          description: list added
        '400':
          description: 'invalid input, object invalid'

  /whitelist:
    post:
      tags:
        - developers
      summary: Adds words to White List
      operationId: addWhiteList
      description:
        Added a list of White List words to the deidentification process to always let thru
      parameters:
        - in: query
          name: deid
          description: list of white words
          required: false
          schema:
            type: string
      responses:
        '201':
          description: list added
        '400':
          description: 'invalid input, object invalid'
  /providers:
    post:
      tags:
        - developers
      summary: Adds provider names to Deid Process
      operationId: addProviderList
      description:
        Added a list of Provider names  to the deidentification process
      parameters:
        - in: query
          name: deid
          description: list of Provider names
          required: false
          schema:
            type: string
      responses:
        '201':
          description: providers  added
        '400':
          description: 'invalid input, object invalid'

  /patients:
    post:
      tags:
        - developers
      summary: Adds Patient List to system
      operationId: addPatientList
      description:
        Added a list of Patients to the deidentification process
      parameters:
        - in: query
          name: deid
          description: list of patient names
          required: false
          schema:
            type: string
      responses:
        '201':
          description: patients added
        '400':
          description: 'invalid input, object invalid'

components:
  schemas:
    DeidResponse:
      type: object
      required:
        - noteId
        - note
      properties:
        noteId:
          type: integer
          format: int32
          example: 1
        note:
          type: string
          example: "[PATIENT] was seen for this procedure"

    DeidRequest:
      type: object
      required:
        - note
        - dateShift
      properties:
        subjectId:
          type: integer
        noteId:
          type: integer
          format: int32
          example: 1
        note:
          type: string
          example: William Doe was seen for this procedure
        daysOffset:
          type: integer
          format: int32
          example: -10
        patientID:
          type: integer
          format: int32
          example: 1234
    Patient:
      required:
        - LastName
        - ID
      properties:
        ID:
          type: integer
          example: 1
        FirstName:
          type: string
          example: William
        LastName:
          type: string
          example: Doe
        mrn:
          type: string
          example: A99999999
        address:
          type: string
          example: 123 E Main
        city:
          type: string
          example: Milwaukee
        zip:
          type: string
          example: 53130
        email:
          type: string
          example: will@noname.com
        birthDate:
          type: string
          example: 12/31/2019
        phone1:
          type: string
          example: 408-867-5309
        phone2:
          type: string
          example: 408-867-5309
        patientAlias:
          $ref: '#/components/schemas/PatientAlias'
      type: object
    PatientAlias:
      type: object
      required:
        - alias
      properties:
        name:
          type: string
          example: "Bill Doe"